#!/bin/bash

CURL=`which curl`
CURL_OPTS='-s --user-agent check-wp-updates-nagios-plugin --insecure'
BASENAME=`which basename`
PROGNAME=`$BASENAME $0`
SSL=/bin/false

# Exit codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

function print_usage
{
	echo "Usage: $PROGNAME -H <hostname> [args]" 
        echo "  -h, --help     Show this help text"
        echo '  -H <hostname>  Hostname to use.'
        echo "  -S             Use SSL (https) instead of http"
	echo "  -P             Path to the remote script. Defaults to wp-version.php"	
}

while test -n "$1"; do
  case "$1" in
    --help)
      print_usage
      exit $STATE_OK
      ;;
    -h)
      print_usage
      exit $STATE_OK
      ;;
    -H)
      hostname=$2
      shift
      ;;
    -S)
      SSL=/bin/true
      ;;
    -P)
      path=$2
      shift
      ;;
    *)
      $ECHO "Unknown argument: $1"
      print_usage
      exit $STATE_UNKNOWN
  esac
  shift
done

# Set a default for hostname
if [ "$hostname" = "" ]; then
  hostname=$NAGIOS_HOSTADDRESS
fi

# Set a default for path
if [ "$path" = "" ]; then
  path="wp-version.php"
fi

# Set the protocol.
if $SSL; then
  protocol="https://"
else
  protocol="http://"
fi

# Check that we're getting a 200 OK message for the wp-version.php file on the remote host. 
response=`$CURL $CURL_OPTS -I ${protocol}${hostname}/$path`
if [[ ( $response != *"200 OK"* && $response != *"HTTP/2 200"* ) ]]; then
        echo 'UNKNOWN - Checker Script not installed on remote host'
        exit $STATE_UNKNOWN
fi


result=`$CURL $CURL_OPTS -s ${protocol}${hostname}/$path`
if [ $? != 0 ]; then
	echo 'UNKNOWN - Check plugin does not work. Maybe you need to install curl.'
	exit $STATE_UNKNOWN
else
	status=`echo $result | cut -d\# -f1`
	text=`echo $result | cut -d\# -f2`

	echo "WORDPRESS $status - $text"
	
	case "$status" in
		CRITICAL)
			exit $STATE_CRITICAL
			;;
		WARNING)
			exit $STATE_WARNING
			;;
		OK)
			exit $STATE_OK
			;;
	esac
  echo "UNKNOWN - Can't parse output from this check.  Make sure your wp-version.php file on the remote WordPress site is not corrupt/modified."
	exit $STATE_UNKNOWN
fi
